export enum Routes {
    AUTH = 'AUTH',

    WELCOME_SCREEN = 'WELCOME_SCREEN',
    REGISTRATION_SCREEN = 'REGISTRATION_SCREEN',
    LOG_IN_SCREEN = 'LOG_IN_SCREEN',

    TABS = 'TABS',

    EVENT_SCREEN = 'EVENT_SCREEN',
    ALL_EVENT_SCREEN = 'ALL_EVENT_SCREEN',

    PROFILE_SCREEN = 'PROFILE_SCREEN',
    MY_PROFILE_SCREEN = 'MY_PROFILE_SCREEN',

    CHAT_SCREEN = 'CHAT_SCREEN',
    ALL_CHAT_SCREEN = 'ALL_CHAT_SCREEN',
};